// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5-KhuBHRxeasXv7gH_XaLvNNgt_itVEc',
    appId: '1:133199136664:web:bcf666bd369deeed78cded',
    messagingSenderId: '133199136664',
    projectId: 'vima-78746',
    authDomain: 'vima-78746.firebaseapp.com',
    storageBucket: 'vima-78746.firebasestorage.app',
    measurementId: 'G-TH8ZN8JMK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp8mSHbCu044fQB_xvTQ_hcb5fNpR9_m4',
    appId: '1:133199136664:android:8cdb299477c3ca9b78cded',
    messagingSenderId: '133199136664',
    projectId: 'vima-78746',
    storageBucket: 'vima-78746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxlkamaTs7VZYsvkuGG1cqtzxuT1nBz1k',
    appId: '1:133199136664:ios:2c16c994e2a8fd7778cded',
    messagingSenderId: '133199136664',
    projectId: 'vima-78746',
    storageBucket: 'vima-78746.firebasestorage.app',
    iosBundleId: 'com.example.moneyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxlkamaTs7VZYsvkuGG1cqtzxuT1nBz1k',
    appId: '1:133199136664:ios:2c16c994e2a8fd7778cded',
    messagingSenderId: '133199136664',
    projectId: 'vima-78746',
    storageBucket: 'vima-78746.firebasestorage.app',
    iosBundleId: 'com.example.moneyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5-KhuBHRxeasXv7gH_XaLvNNgt_itVEc',
    appId: '1:133199136664:web:ef3aa4c919a984ba78cded',
    messagingSenderId: '133199136664',
    projectId: 'vima-78746',
    authDomain: 'vima-78746.firebaseapp.com',
    storageBucket: 'vima-78746.firebasestorage.app',
    measurementId: 'G-P93RS6Z1TK',
  );
}
